seckill:
  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/wh_seckill
      username: root
      password: wxl2001072312
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: archester-250 is so awesome!!!!!!!!!!!!!!!!!!1
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token